### ISSUE TITLE
Unable to log into mysql

### ISSUE THREAD

**Issue by asamuelson14** [codio-content/MySQL_Playground#1]
Hello,

I would love to use this course for my Computer Science Year 11 students. I am testing it out, and it is a fantastic resource. However, when I follow the directions and try to start mysql, I am told that access is denied. I have attached a screenshot for your reference. I can start the server by typing _mysql -u root_, but then I do not have access to the _people_ database needed to complete the course. Thank you for any help you can provide.

Regards,
Andrea 
![mysql](https://cloud.githubusercontent.com/assets/21689429/18174037/e60d2e04-7063-11e6-9ae7-40f531542d10.PNG)

**Comment by ksimuk** [comment]
@asamuelson14 thank you for feedback, with what unit do you have this issue? have you created the unit from our course or you select mysql stack and used project from github? please check you are using https://codio.com/home/stacks/b0e81f90-8b77-40f6-8040-090d314e0803/?tab=details stack, it doesn't require authentication for mysql for codio user, for the standard mysql stack you can type `sudo mysql` to get root user access to mysql.

Thank you

**Comment by asamuelson14** [comment]
Ok, it works now that I am using the correct stack. Thank you very much for your help.
